### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [evernym/sovrin-client-rust#36]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by dhh1128** [comment]
@vimmerru Can you please look at this?

**Comment by vimmerru** [comment]
We are already in discussion of this. We have few issues with rustc-serialize and considering switching to serde. Most probable we will completely switch to serde in few days.

**Comment by vimmerru** [comment]
We removed rustc-serialize dependency in this merged PR https://github.com/evernym/sovrin-client-rust/pull/39 and switched to usage of serde for serialization/deserialization functionality.
