### ISSUE TITLE
No "cb" parameter in sovrin_register_wallet_type

### ISSUE THREAD

**Issue by peacekeeper** [evernym/sovrin-client-rust#52]
I realize the sovrin_register_wallet_type method will be implemented in a later version, but still it seems to be the only method in the entire library that doesn't have the "cb" callback parameter. Should this be added?

**Comment by dhh1128** [comment]
I think it's not asynchronous, so there's not point in having a callback. But you're right, that does sign us up for a slight inconsistency. I suspect there will be a handful of other functions that are not async by the time we are done (e.g., some utilities).

**Comment by vimmerru** [comment]
For the current moment we have 2 reasons for async functions:

1. Avoid blocking of user thread in IO if current operation causes network/disk IO.
2. Avoid transfer of library allocated memory ownership to the user side. All pointers in callback are valid only during callback call time and corresponded memory will be freed after finishing of callback call.

sovrin_register_wallet_type doesn't correspond to this reasons, so sync interface for this call looks reasonable for me.

Also, sovrin_register_wallet_type call has 2nd priority as it is more point of library extension than main functionality. Most probable this call will be missed in first libsovrin release. We are still in discussion of low-level requirements for wallets and there is high probability that signature of this call can be changed before it will be released.

@peacekeeper @dhh1128 If you think that this question is answered we can close this ticket.

**Comment by peacekeeper** [comment]
Yes makes a lot of sense, thank you!
