### ISSUE TITLE
pool_handle vs. pool_name?

### ISSUE THREAD

**Issue by peacekeeper** [evernym/sovrin-client-rust#53]
`sovrin_open_wallet` needs a `pool_handle` parameter, but `sovrin_create_wallet` needs a `pool_name` parameter. Why?

`sovrin_open_pool_ledger` only returns a `pool_handle`, so how would one get the `pool_name`?

**Comment by dhh1128** [comment]
@vimmerru

**Comment by vimmerru** [comment]
Libsovrin allows the user to work with different pools. For example, it can be some "Sandbox" pool used for testing and "Sovrin" pool that corresponds to pool managed by Sovrin Foundation.  

Same situation with wallets. It is possible to create and use multiple wallets. For example, agent can manage multiple wallets for different users. 

Each pool and wallet have persistence ability and we need some way to identify corresponded files. "pool_name" and "wallet_name" are used for this long-term identification. 

Also to use pool or wallet we need to create some corresponded runtime objects that are identified by "wallet_handle" and "pool_handle". User manages lifetime of this object so we provide correspoded "open" and "close" functions.

Note that wallet stores identity information that has the meaning only for one pool. Different pool has different transactions, different id's and etc... As result wallet needs to store information about pool for which it was created. It is why sovrin_create_wallet requires pool name parameter.

"sovrin_open_pool_ledger" - requires "pool_name", creates corresponded runtime object and returns corresponded handle ("pool_handle").

"sovrin_open_wallet" - requires "wallet_name", creates correspinded runtime object and returns corresponded handle ("wallet_handle"). It is additionally requires access to runtime object for compatible pool. 

> sovrin_open_wallet needs a pool_handle parameter, but sovrin_create_wallet needs a pool_name parameter. Why?

sovrin_create_wallet doesn't need to access pool runtime object and only stores "pool_name" and methadata file that sovrin_create_wallet creates for future checking of wallet and pool compatibility.

In case of sovrin_open_wallet we require "pool_handle" to avoid of providing both pool_handle and wallet_handle in signus calls. For now i see that it isn't good idea as there are use cases when wallet can be used without pool ledger. I will create separate ticket for this.

> sovrin_open_pool_ledger only returns a pool_handle, so how would one get the pool_name?

sovrin_open_pool_ledge requires "pool_name" as parameter. User assings "pool_name" when calls sovrin_create_pool_ledger. Same name should be provided to sovrin_create_wallet.

**Comment by vimmerru** [comment]
> For now i see that it isn't good idea as there are use cases when wallet can be used without pool ledger. I will create separate ticket for this.

We decided to remove `pool_handle` parameter from `sovrin_open_wallet` to be able to use the wallet for cases when we don't need access to the pool. For example, now you can put most of the crypto staff to dedicated secure machine without network access. For cases when API requires access to the pool and the wallet at the same time, you need to provide both handles. For example, in few Signus API methods. 

Checking off wallet and pool are compatible will be performed in Signus API methods in runtime.
