### ISSUE TITLE
Cargo build failed on Mac OS X Sierra

### ISSUE THREAD

**Issue by JosCline** [evernym/sovrin-client-rust#84]
Once I cloned this repo, I tried to 'cargo build' this on a Mac OS X Sierra and got this error:
error: failed to run custom build command for `libsodium-sys v0.0.14`
process didn't exit successfully: `/Users/josephcline/rust_projects/sovrin-client-rust/target/debug/build/libsodium-sys-c81c2aab8a6cece2/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"`: No such file or directory (os error 2)"', src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by dhh1128** [comment]
@vimmerru I am guessing this is a problem with a build script containing linux-specific code? If so, we need to fix. This build should run on OSX, linux, and Windows.

**Comment by vimmerru** [comment]
There is nothing linux-specific in our build scripts, but we depend on multiple native libraries. 

To build libsovrin we need the following 3d party packages installed:

pkg-config
libzmq3
libssl
curl
libsqlite3
libsodium
cmake
milagro-crypto-c

This error means that there is no pkg-config installed on the host system. Tasks for support of Windows, iOS and MacOS are in our backlog. We are working right now on the support of Windows and iOS and will provide corresponded instructions soon. MacOS support will be started a bit later.

**Comment by snemesh** [comment]
How to fix it? I have the same problem. I tried to install all this packages, and after that I run this command in console: "cargo run" and received this error again. Please help.

**Comment by vimmerru** [comment]
This repo is outdated. Please move to https://github.com/hyperledger/indy-sdk and check latest MacOS instruction https://github.com/hyperledger/indy-sdk/blob/master/doc/mac-build.md.

**Comment by vimmerru** [comment]
Also, I suggest checking readme.md in https://github.com/hyperledger/indy-sdk repo. It contain's the link to Jira project and RocketChat chat that can be used for getting support.
